package Entities;
// Generated 08-mar-2015 15:56:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private String telefono;
     private String ci;
     private byte[] edad;
     private Set ratreos = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(int id) {
        this.id = id;
    }
    public Paciente(int id, String nombre, String apellido, String telefono, String ci, byte[] edad, Set ratreos) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.ci = ci;
       this.edad = edad;
       this.ratreos = ratreos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public byte[] getEdad() {
        return this.edad;
    }
    
    public void setEdad(byte[] edad) {
        this.edad = edad;
    }
    public Set getRatreos() {
        return this.ratreos;
    }
    
    public void setRatreos(Set ratreos) {
        this.ratreos = ratreos;
    }




}


