package Entities;
// Generated 09-mar-2015 19:39:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Resonancia generated by hbm2java
 */
public class Resonancia  implements java.io.Serializable {


     private int id;
     private String description;
     private String localizacion;
     private Set pars = new HashSet(0);

    public Resonancia() {
    }

	
    public Resonancia(int id) {
        this.id = id;
    }
    public Resonancia(int id, String description, String localizacion, Set pars) {
       this.id = id;
       this.description = description;
       this.localizacion = localizacion;
       this.pars = pars;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }
    public Set getPars() {
        return this.pars;
    }
    
    public void setPars(Set pars) {
        this.pars = pars;
    }




}


